version: '3.1'
services:
  nginx:
    #image: nginx:latest
    build: ./nginx/
    container_name: nginx_container
    restart: unless-stopped
    tty: true
    env_file:
      - test.env
    environment:
      - NGINX_PORT=80
      - HTTP_AUTH_LOGIN
      - HTTP_AUTH_PASSWORD
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - data-volume:/var/www/html
    links:
      - php
    depends_on:
      - php


  php:
    # image: meda10/bp_tor_php:with_files
    build: ./php/
    container_name: php_container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    expose:
      - 9000
    networks:
      - app-network
    volumes:
      - data-volume:/var/www/html/Tor-simulations/www/html

volumes:
     data-volume:

networks:
  app-network:
    driver: bridge

